### PR TITLE
Added 1.20 Support

### PR DESCRIPTION
**Pull request by r3back**
Changes List:

- Added 1.20.0 NMS Support
- Updated build.gradle version

### CODE REVIEW

**Comment by boiscljo** [comment]
This would not add 1.20 support as NBTAPI and XMaterial versions are not updated. Since 1.19.3 NMS doesn`t include version specific and does not need this update anymore. The default implementation is enough for the core since.

**Comment by r3back** [comment]
Oh that's true, I ignored the default implementation, it already seemed strange to me that imports between 1.19.3 and 1.20 did not have substantial differences, but I forgot to look in depth at the default module, add the changes required for 1.20 support

**Comment by boiscljo** [comment]
I forwarded the info to @PeachesMLG so he could merge it now that it supports 1.20

**Comment by r3back** [comment]
Perfect, additionally i added the required version changes in IridiumTeams and IridiumSkyblock which i understand are necesaries in order to keep them updated with these changes.

**Pull request merged**
